### ISSUE TITLE
Linux (Ubuntu) : Unable to use

### ISSUE THREAD

**Issue by LoganTann** [cheshire137/svtools#2]
## Issue summary

I tried the command inside the README.md file, and tried other arguments, but the program returns me always the help.

## System

OS : Xubuntu 18.04.4
Installed go using the snap store (`sudo snap install go --classic`) -> go version 1.14.2
Compiled using `make`

## Input / Output
input : 
```sh
$ bin/svtools samples/Sarah_116989742 
$ bin/svtools samples/Sarah_116989742 .
$ bin/svtools samples/Sarah_116989742  samples/test
$ bin/svtools ./samples/Sarah_116989742 .
$ ./bin/svtools ./samples/Sarah_116989742 .
$ ./bin/svtools ./samples/Sarah_116989742 ./
$ ./bin/svtools ./samples/Sarah_116989742 ./samples/Sarah_116989742 
$ ./bin/svtools ./samples/Sarah_116989742 ./samples/Sarah_116989742.bak
```
Output (same for every commands) : 
```
  -in string
    	Path to a Stardew Valley save file, e.g, /Users/yourMacUser/.config/StardewValley/Saves/YourStardewCharacter_116989742/YourStardewCharacter_116989742
  -out string
    	Path to where a duplicate of the specified save file should be made
```

**Comment by cheshire137** [comment]
Ahh I think I left the readme in a state out of sync with the actual script. 🙈 This is definitely still a work in progress, so it doesn't do much of anything right now!
